# TASK 4.8.
# Table of Contents
## 1. Import libraries and data set
## 2. Find the aggregated mean of the “order_number” column grouped by “department_id" for the entire dataframe
## 3. Comments about differences of these results and results for the same action using a subset
## 4. Create a loyalty flag for existing customers using the transform() and loc() functions
## 5. Check the basic statistics of the product prices for each loyalty category
## 6. Create a spending flag
## 7. Create an order frequency flag
## 8. Export dataframe

---

## 1. Import libraries and data set

1. Create a new notebook for this task. Be sure to import the relevant libraries, along with your ords_prods_merge dataframe, which should include your newly derived columns from the previous Exercise.

In [21]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [23]:
path = r'/Users/mariliamachado/Documents/CareerFoundry/11-2024 Instacart Basket Analysis'

In [25]:
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_4_8.pkl'))

## 2. Find the aggregated mean of the “order_number” column grouped by “department_id" for the entire dataframe

2. In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the entire dataframe.

In [15]:
ords_prods_merge.shape

(32404859, 18)

In [17]:
ords_prods_merge.head(10)

,order_id,user_id,order_number,orders_day_of_week,order_time_hour,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,match,max_order,loyalty_flag
0,2539329,1,1,2,8,NaN,True,196,1,0,both,Soda,77,7,9.0,both,10,New customer
1,2539329,1,1,2,8,NaN,True,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,10,New customer
2,2539329,1,1,2,8,NaN,True,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,10,New customer
3,2539329,1,1,2,8,NaN,True,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,10,New customer
4,2539329,1,1,2,8,NaN,True,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,10,New customer
5,2398795,1,2,3,7,15.0,False,196,1,1,both,Soda,77,7,9.0,both,10,New customer
6,2398795,1,2,3,7,15.0,False,10258,2,0,both,Pistachios,117,19,3.0,both,10,New customer
7,2398795,1,2,3,7,15.0,False,12427,3,1,both,Original Beef Jerky,23,19,4.4,both,10,New customer
8,2398795,1,2,3,7,15.0,False,13176,4,0,both,Bag of Organic Bananas,24,4,10.3,both,10,New customer
9,2398795,1,2,3,7,15.0,False,26088,5,1,both,Aged White Cheddar Popcorn,23,19,4.7,both,10,New customer

In [11]:
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

## 3. Comments about differences of these results and results for the same action using a subset

3. Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code.

In general, the mean values are higher in the entire dataframe than in the subset. However, the difference is very small, no more than 1.0 usually, so the subset still gives us a pretty accurate idea of the entire dataset.

## 4. Create a loyalty flag for existing customers using the transform() and loc() functions

4. Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.

I thought that the df I should import was the one from this exercise, I have already done it while learning about creating a flag, so the column is already created. However, I'll do it again for the purpose of the task and drop the extra columns later.

In [37]:
ords_prods_merge['max_order_2'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

/var/folders/1l/dnjb8fld07b4wz73yz4dyxqw0000gn/T/ipykernel_66995/3484954393.py:1: FutureWarning: The provided callable <function max at 0x110448680> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ords_prods_merge['max_order_2'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [43]:
pd.options.display.max_rows = None

In [45]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_time_hour,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,match,max_order,loyalty_flag,max_order_2
0,2539329,1,1,2,8,NaN,True,196,1,0,both,Soda,77,7,9.0,both,10,New customer,10
1,2539329,1,1,2,8,NaN,True,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,10,New customer,10
2,2539329,1,1,2,8,NaN,True,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,10,New customer,10
3,2539329,1,1,2,8,NaN,True,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,10,New customer,10
4,2539329,1,1,2,8,NaN,True,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,10,New customer,10
5,2398795,1,2,3,7,15.0,False,196,1,1,both,Soda,77,7,9.0,both,10,New customer,10
6,2398795,1,2,3,7,15.0,False,10258,2,0,both,Pistachios,117,19,3.0,both,10,New customer,10
7,2398795,1,2,3,7,15.0,False,12427,3,1,both,Original Beef Jerky,23,19,4.4,both,10,New customer,10
8,2398795,1,2,3,7,15.0,False,13176,4,0,both,Bag of Organic Bananas,24,4,10.3,both,10,New customer,10
9,2398795,1,2,3,7,15.0,False,26088,5,1,both,Aged White Cheddar Popcorn,23,19,4.7,both,10,New customer,10
10,2398795,1,2,3,7,15.0,False,13032,6,0,both,Cinnamon Toast Crunch,121,14,4.0,both,10,New customer,10
11,473747,1,3,3,12,21.0,False,196,1,1,both,Soda,77,7,9.0,both,10,New customer,10
12,473747,1,3,3,12,21.0,False,12427,2,1,both,Original Beef Jerky,23,19,4.4,both,10,New customer,10
13,473747,1,3,3,12,21.0,False,10258,3,1,both,Pistachios,117,19,3.0,both,10,New customer,10
14,473747,1,3,3,12,21.0,False,25133,4,0,both,Organic String Cheese,21,16,8.6,both,10,New customer,10
15,473747,1,3,3,12,21.0,False,30450,5,0,both,Creamy Almond Butter,88,13,3.2,both,10,New customer,10
16,2254736,1,4,4,7,29.0,False,196,1,1,both,Soda,77,7,9.0,both,10,New customer,10
17,2254736,1,4,4,7,29.0,False,12427,2,1,both,Original Beef Jerky,23,19,4.4,both,10,New customer,10
18,2254736,1,4,4,7,29.0,False,10258,3,1,both,Pistachios,117,19,3.0,both,10,New customer,10
19,2254736,1,4,4,7,29.0,False,25133,4,1,both,Organic String Cheese,21,16,8.6,both,10,New customer,10
20,2254736,1,4,4,7,29.0,False,26405,5,1,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,10,New customer,10
21,431534,1,5,4,15,28.0,False,196,1,1,both,Soda,77,7,9.0,both,10,New customer,10
22,431534,1,5,4,15,28.0,False,12427,2,1,both,Original Beef Jerky,23,19,4.4,both,10,New customer,10
23,431534,1,5,4,15,28.0,False,10258,3,1,both,Pistachios,117,19,3.0,both,10,New customer,10
24,431534,1,5,4,15,28.0,False,25133,4,1,both,Organic String Cheese,21,16,8.6,both,10,New customer,10
25,431534,1,5,4,15,28.0,False,10326,5,0,both,Organic Fuji Apples,24,4,2.7,both,10,New customer,10
26,431534,1,5,4,15,28.0,False,17122,6,0,both,Honeycrisp Apples,24,4,14.0,both,10,New customer,10
27,431534,1,5,4,15,28.0,False,41787,7,0,both,Bartlett Pears,24,4,5.0,both,10,New customer,10
28,431534,1,5,4,15,28.0,False,13176,8,1,both,Bag of Organic Bananas,24,4,10.3,both,10,New customer,10
29,3367565,1,6,2,7,19.0,False,196,1,1,both,Soda,77,7,9.0,both,10,New customer,10
30,3367565,1,6,2,7,19.0,False,12427,2,1,both,Original Beef Jerky,23,19,4.4,both,10,New customer,10
31,3367565,1,6,2,7,19.0,False,10258,3,1,both,Pistachios,117,19,3.0,both,10,New customer,10
32,3367565,1,6,2,7,19.0,False,25133,4,1,both,Organic String Cheese,21,16,8.6,both,10,New customer,10
33,550135,1,7,1,9,20.0,False,196,1,1,both,Soda,77,7,9.0,both,10,New customer,10
34,550135,1,7,1,9,20.0,False,10258,2,1,both,Pistachios,117,19,3.0,both,10,New customer,10
35,550135,1,7,1,9,20.0,False,12427,3,1,both,Original Beef Jerky,23,19,4.4,both,10,New customer,10
36,550135,1,7,1,9,20.0,False,25133,4,1,both,Organic String Cheese,21,16,8.6,both,10,New customer,10
37,550135,1,7,1,9,20.0,False,13032,5,1,both,Cinnamon Toast Crunch,121,14,4.0,both,10,New customer,10
38,3108588,1,8,1,14,14.0,False,12427,1,1,both,Original Beef Jerky,23,19,4.4,both,10,New customer,10
39,3108588,1,8,1,14,14.0,False,196,2,1,both,Soda,77,7,9.0,both,10,New customer,10
40,3108588,1,8,1,14,14.0,False,10258,3,1,both,Pistachios,117,19,3.0,both,10,New customer,10
41,3108588,1,8,1,14,14.0,False,25133,4,1,both,Organic String Cheese,21,16,8.6,both,10,New customer,10
42,3108588,1,8,1,14,14.0,False,46149,5,0,both,Zero Calorie Cola,77,7,13.4,both,10,New customer,10
43,3108588,1,8,1,14,14.0,False,49235,6,0,both,Organic Half & Half,53,16,1.8,both,10,New customer,10
44,2295261,1,9,1,16,0.0,False,49235,1,1,both,Organic Half & Half,53,16,1.8,both,10,New customer,10
45,2295261,1,9,1,16,0.0,False,46149,2,1,both,Zero Calorie Cola,77,7,13.4,both,10,New customer,10
46,2295261,1,9,1,16,0.0,False,25133,3,1,both,Organic String Cheese,21,16,8.6,both,10,New customer,10
47,2295261,1,9,1,16,0.0,False,196,4,1,both,Soda,77,7,9.0,both,10,New customer,10
48,2295261,1,9,1,16,0.0,False,10258,5,1,both,Pistachios,117,19,3.0,both,10,New customer,10
49,2295261,1,9,1,16,0.0,False,12427,6,1,both,Original Beef Jerky,23,19,4.4,both,10,New customer,10
50,2550362,1,10,4,8,30.0,False,196,1,1,both,Soda,77,7,9.0,both,10,New customer,10
51,2550362,1,10,4,8,30.0,False,46149,2,1,both,Zero Calorie Cola,77,7,13.4,both,10,New customer,10
52,2550362,1,10,4,8,30.0,False,39657,3,0,both,Milk Chocolate Almonds,45,19,6.8,both,10,New customer,10
53,2550362,1,10,4,8,30.0,False,38928,4,0,both,0% Greek Strained Yogurt,120,16,12.6,both,10,New customer,10
54,2550362,1,10,4,8,30.0,False,25133,5,1,both,Organic String Cheese,21,16,8.6,both,10,New customer,10
55,2550362,1,10,4,8,30.0,False,10258,6,1,both,Pistachios,117,19,3.0,both,10,New customer,10
56,2550362,1,10,4,8,30.0,False,35951,7,0,both,Organic Unsweetened Almond Milk,91,16,1.3,both,10,New customer,10
57,2550362,1,10,4,8,30.0,False,13032,8,1,both,Cinnamon Toast Crunch,121,14,4.0,both,10,New customer,10
58,2550362,1,10,4,8,30.0,False,12427,9,1,both,Original Beef Jerky,23,19,4.4,both,10,New customer,10
59,2168274,2,1,2,11,NaN,True,32792,1,0,both,Chipotle Beef & Pork Realstick,23,19,5.2,both,14,Regular customer,14
60,2168274,2,1,2,11,NaN,True,47766,2,0,both,Organic Avocado,24,4,6.3,both,14,Regular customer,14
61,2168274,2,1,2,11,NaN,True,20574,3,0,both,Roasted Turkey,96,20,2.3,both,14,Regular customer,14
62,2168274,2,1,2,11,NaN,True,12000,4,0,both,Baked Organic Sea Salt Crunchy Pea Snack,72,13,10.9,both,14,Regular customer,14
63,2168274,2,1,2,11,NaN,True,48110,5,0,both,Thin Stackers Brown Rice Lightly Salted,78,19,2.7,both,14,Regular customer,14
64,2168274,2,1,2,11,NaN,True,22474,6,0,both,Cheddar Bunnies Snack Crackers,78,19,4.1,both,14,Regular customer,14
65,2168274,2,1,2,11,NaN,True,16589,7,0,both,Plantain Chips,107,19,5.0,both,14,Regular customer,14
66,2168274,2,1,2,11,NaN,True,35917,8,0,both,Organic Just Concord Grape Juice,98,7,9.4,both,14,Regular customer,14
67,2168274,2,1,2,11,NaN,True,27344,9,0,both,Uncured Genoa Salami,96,20,14.8,both,14,Regular customer,14
68,2168274,2,1,2,11,NaN,True,30489,10,0,both,Original Hummus,67,20,7.5,both,14,Regular customer,14
69,2168274,2,1,2,11,NaN,True,27966,11,0,both,Organic Raspberries,123,4,4.4,both,14,Regular customer,14
70,2168274,2,1,2,11,NaN,True,13176,12,0,both,Bag of Organic Bananas,24,4,10.3,both,14,Regular customer,14
71,2168274,2,1,2,11,NaN,True,45066,13,0,both,Honeycrisp Apple,24,4,2.5,both,14,Regular customer,14
72,1501582,2,2,5,10,10.0,False,16797,1,0,both,Strawberries,24,4,1.3,both,14,Regular customer,14
73,1501582,2,2,5,10,10.0,False,47526,2,0,both,Goat Cheese Log,21,16,2.0,both,14,Regular customer,14
74,1501582,2,2,5,10,10.0,False,8479,3,0,both,Original Black Box Tablewater Cracker,78,19,3.5,both,14,Regular customer,14
75,1501582,2,2,5,10,10.0,False,47766,4,1,both,Organic Avocado,24,4,6.3,both,14,Regular customer,14
76,1501582,2,2,5,10,10.0,False,19051,5,0,both,"Pita Chips, Simply Naked, Party Size",107,19,3.9,both,14,Regular customer,14
77,1501582,2,2,5,10,10.0,False,8138,6,0,both,Traditional Hummus,67,20,2.0,both,14,Regular customer,14
78,1901567,2,3,1,10,3.0,False,47766,1,1,both,Organic Avocado,24,4,6.3,both,14,Regular customer,14
79,1901567,2,3,1,10,3.0,False,32792,2,1,both,Chipotle Beef & Pork Realstick,23,19,5.2,both,14,Regular customer,14
80,1901567,2,3,1,10,3.0,False,20574,3,1,both,Roasted Turkey,96,20,2.3,both,14,Regular customer,14
81,1901567,2,3,1,10,3.0,False,7781,4,0,both,Organic Sticks Low Moisture Part Skim Mozzarel...,21,16,6.6,both,14,Regular customer,14
82,1901567,2,3,1,10,3.0,False,28874,5,0,both,Carrot Ginger Soup,1,20,6.2,both,14,Regular customer,14
83,738281,2,4,2,10,8.0,False,49451,1,0,both,Artichoke Spinach Dip,67,20,7.1,both,14,Regular customer,14
84,738281,2,4,2,10,8.0,False,32792,2,1,both,Chipotle Beef & Pork Realstick,23,19,5.2,both,14,Regular customer,14
85,738281,2,4,2,10,8.0,False,32139,3,0,both,Hommus Classic Original,67,20,7.5,both,14,Regular customer,14
86,738281,2,4,2,10,8.0,False,34688,4,0,both,Good Belly Probiotics Juice Drink Blueberry Ac...,31,7,5.8,both,14,Regular customer,14
87,738281,2,4,2,10,8.0,False,36735,5,0,both,Organic Roasted Sliced Chicken Breast,96,20,8.9,both,14,Regular customer,14
88,738281,2,4,2,10,8.0,False,37646,6,0,both,Organic Gala Apples,24,4,9.1,both,14,Regular customer,14
89,738281,2,4,2,10,8.0,False,22829,7,0,both,Multigrain Flax Seeded Flatbread Crackers,78,19,5.5,both,14,Regular customer,14
90,738281,2,4,2,10,8.0,False,24852,8,0,both,Banana,24,4,12.3,both,14,Regular customer,14
91,738281,2,4,2,10,8.0,False,47209,9,0,both,Organic Hass Avocado,24,4,4.0,both,14,Regular customer,14
92,738281,2,4,2,10,8.0,False,33276,10,0,both,Kalamata Olive Spread,67,20,10.8,both,14,Regular customer,14
93,738281,2,4,2,10,8.0,False,45613,11,0,both,Pad Thai,38,1,12.6,both,14,Regular customer,14
94,738281,2,4,2,10,8.0,False,9681,12,0,both,Chicken Tikka Masala with Cumin Infused Basmat...,38,1,2.0,both,14,Regular customer,14
95,738281,2,4,2,10,8.0,False,21150,13,0,both,Fire Grilled Steak Bowl,38,1,5.9,both,14,Regular customer,14
96,1673511,2,5,3,11,8.0,False,47144,1,0,both,Unsweetened Original Almond Breeze Almond Milk,91,16,14.0,both,14,Regular customer,14
97,1673511,2,5,3,11,8.0,False,5322,2,0,both,Gluten Free Dark Chocolate Chunk Chewy with a ...,3,19,2.9,both,14,Regular customer,14
98,1673511,2,5,3,11,8.0,False,17224,3,0,both,Oats & Honey Gluten Free Granola,3,19,1.6,both,14,Regular customer,14
99,1673511,2,5,3,11,8.0,False,38656,4,0,both,Gluten Free Peanut Butter Dark Chocolate Chewy...,3,19,3.4,both,14,Regular customer,14

In [47]:
ords_prods_merge.loc[ords_prods_merge['max_order_2'] > 40, 'loyalty_flag_2'] = 'Loyal customer'
ords_prods_merge.loc[(ords_prods_merge['max_order_2'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag_2'] = 'Regular customer'
ords_prods_merge.loc[ords_prods_merge['max_order_2'] <= 10, 'loyalty_flag_2'] = 'New customer'

In [54]:
# Check value counts on loyalty_flag_2
ords_prods_merge['loyalty_flag_2'].value_counts(dropna = False)

loyalty_flag_2
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [31]:
ords_prods_merge['max_order'].value_counts(dropna = False)

max_order
99    1171333
8      811843
6      811396
9      810213
7      803979
       ...
97      44949
98      44587
96      40453
2           6
1           5
Name: count, Length: 99, dtype: int64

## 5. Check the basic statistics of the product prices for each loyalty category

5. The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

In [56]:
ords_prods_merge.groupby('loyalty_flag_2').agg({'prices' : ['mean', 'min', 'max']})

                    prices
                      mean  min   max
loyalty_flag_2
Loyal customer    7.773832  1.0  25.0
New customer      7.801554  1.0  25.0
Regular customer  7.798580  1.0  25.0

New customers spend more on average, but the difference is not big. Loyal customers seem to purchase lower-cost products, followed by regular customers and then loyal customers. All brackets of clients purchase the same minimum of 1 and the same maximum of 25, which suggests there might be a cap in terms of pricing in this dataset, or those are indeed the cheapest or most expensive products you can purchase on Instacart.

## 6. Create a spending flag

6. The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:
   - If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
   - If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [59]:
#Create column with average price orders
ords_prods_merge['average_price_orders'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

/var/folders/1l/dnjb8fld07b4wz73yz4dyxqw0000gn/T/ipykernel_66995/3160245152.py:1: FutureWarning: The provided callable <function mean at 0x110449080> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  ords_prods_merge['average_price_orders'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [65]:
ords_prods_merge[['user_id', 'average_price_orders']].head(100)

    user_id  average_price_orders
0         1              6.367797
1         1              6.367797
2         1              6.367797
3         1              6.367797
4         1              6.367797
5         1              6.367797
6         1              6.367797
7         1              6.367797
8         1              6.367797
9         1              6.367797
10        1              6.367797
11        1              6.367797
12        1              6.367797
13        1              6.367797
14        1              6.367797
15        1              6.367797
16        1              6.367797
17        1              6.367797
18        1              6.367797
19        1              6.367797
20        1              6.367797
21        1              6.367797
22        1              6.367797
23        1              6.367797
24        1              6.367797
25        1              6.367797
26        1              6.367797
27        1              6.367797
28        1              6.367797
29        1              6.367797
30        1              6.367797
31        1              6.367797
32        1              6.367797
33        1              6.367797
34        1              6.367797
35        1              6.367797
36        1              6.367797
37        1              6.367797
38        1              6.367797
39        1              6.367797
40        1              6.367797
41        1              6.367797
42        1              6.367797
43        1              6.367797
44        1              6.367797
45        1              6.367797
46        1              6.367797
47        1              6.367797
48        1              6.367797
49        1              6.367797
50        1              6.367797
51        1              6.367797
52        1              6.367797
53        1              6.367797
54        1              6.367797
55        1              6.367797
56        1              6.367797
57        1              6.367797
58        1              6.367797
59        2              7.515897
60        2              7.515897
61        2              7.515897
62        2              7.515897
63        2              7.515897
64        2              7.515897
65        2              7.515897
66        2              7.515897
67        2              7.515897
68        2              7.515897
69        2              7.515897
70        2              7.515897
71        2              7.515897
72        2              7.515897
73        2              7.515897
74        2              7.515897
75        2              7.515897
76        2              7.515897
77        2              7.515897
78        2              7.515897
79        2              7.515897
80        2              7.515897
81        2              7.515897
82        2              7.515897
83        2              7.515897
84        2              7.515897
85        2              7.515897
86        2              7.515897
87        2              7.515897
88        2              7.515897
89        2              7.515897
90        2              7.515897
91        2              7.515897
92        2              7.515897
93        2              7.515897
94        2              7.515897
95        2              7.515897
96        2              7.515897
97        2              7.515897
98        2              7.515897
99        2              7.515897

In [67]:
# Create spending_flag
ords_prods_merge.loc[ords_prods_merge['average_price_orders'] < 10, 'spending_flag'] = 'Low spender'
ords_prods_merge.loc[(ords_prods_merge['average_price_orders'] >= 10), 'spending_flag'] = 'High spender'

In [69]:
# Check value counts on the spending_flag
ords_prods_merge['spending_flag'].value_counts(dropna = False)

spending_flag
Low spender     32285131
High spender      119728
Name: count, dtype: int64

In [73]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_time_hour,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,match,max_order,loyalty_flag,max_order_2,loyalty_flag_2,average_price_orders,spending_flag
0,2539329,1,1,2,8,NaN,True,196,1,0,...,77,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender
1,2539329,1,1,2,8,NaN,True,14084,2,0,...,91,16,12.5,both,10,New customer,10,New customer,6.367797,Low spender
2,2539329,1,1,2,8,NaN,True,12427,3,0,...,23,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender
3,2539329,1,1,2,8,NaN,True,26088,4,0,...,23,19,4.7,both,10,New customer,10,New customer,6.367797,Low spender
4,2539329,1,1,2,8,NaN,True,26405,5,0,...,54,17,1.0,both,10,New customer,10,New customer,6.367797,Low spender
5,2398795,1,2,3,7,15.0,False,196,1,1,...,77,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender
6,2398795,1,2,3,7,15.0,False,10258,2,0,...,117,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender
7,2398795,1,2,3,7,15.0,False,12427,3,1,...,23,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender
8,2398795,1,2,3,7,15.0,False,13176,4,0,...,24,4,10.3,both,10,New customer,10,New customer,6.367797,Low spender
9,2398795,1,2,3,7,15.0,False,26088,5,1,...,23,19,4.7,both,10,New customer,10,New customer,6.367797,Low spender
10,2398795,1,2,3,7,15.0,False,13032,6,0,...,121,14,4.0,both,10,New customer,10,New customer,6.367797,Low spender
11,473747,1,3,3,12,21.0,False,196,1,1,...,77,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender
12,473747,1,3,3,12,21.0,False,12427,2,1,...,23,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender
13,473747,1,3,3,12,21.0,False,10258,3,1,...,117,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender
14,473747,1,3,3,12,21.0,False,25133,4,0,...,21,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender
15,473747,1,3,3,12,21.0,False,30450,5,0,...,88,13,3.2,both,10,New customer,10,New customer,6.367797,Low spender
16,2254736,1,4,4,7,29.0,False,196,1,1,...,77,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender
17,2254736,1,4,4,7,29.0,False,12427,2,1,...,23,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender
18,2254736,1,4,4,7,29.0,False,10258,3,1,...,117,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender
19,2254736,1,4,4,7,29.0,False,25133,4,1,...,21,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender
20,2254736,1,4,4,7,29.0,False,26405,5,1,...,54,17,1.0,both,10,New customer,10,New customer,6.367797,Low spender
21,431534,1,5,4,15,28.0,False,196,1,1,...,77,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender
22,431534,1,5,4,15,28.0,False,12427,2,1,...,23,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender
23,431534,1,5,4,15,28.0,False,10258,3,1,...,117,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender
24,431534,1,5,4,15,28.0,False,25133,4,1,...,21,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender
25,431534,1,5,4,15,28.0,False,10326,5,0,...,24,4,2.7,both,10,New customer,10,New customer,6.367797,Low spender
26,431534,1,5,4,15,28.0,False,17122,6,0,...,24,4,14.0,both,10,New customer,10,New customer,6.367797,Low spender
27,431534,1,5,4,15,28.0,False,41787,7,0,...,24,4,5.0,both,10,New customer,10,New customer,6.367797,Low spender
28,431534,1,5,4,15,28.0,False,13176,8,1,...,24,4,10.3,both,10,New customer,10,New customer,6.367797,Low spender
29,3367565,1,6,2,7,19.0,False,196,1,1,...,77,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender
30,3367565,1,6,2,7,19.0,False,12427,2,1,...,23,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender
31,3367565,1,6,2,7,19.0,False,10258,3,1,...,117,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender
32,3367565,1,6,2,7,19.0,False,25133,4,1,...,21,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender
33,550135,1,7,1,9,20.0,False,196,1,1,...,77,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender
34,550135,1,7,1,9,20.0,False,10258,2,1,...,117,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender
35,550135,1,7,1,9,20.0,False,12427,3,1,...,23,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender
36,550135,1,7,1,9,20.0,False,25133,4,1,...,21,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender
37,550135,1,7,1,9,20.0,False,13032,5,1,...,121,14,4.0,both,10,New customer,10,New customer,6.367797,Low spender
38,3108588,1,8,1,14,14.0,False,12427,1,1,...,23,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender
39,3108588,1,8,1,14,14.0,False,196,2,1,...,77,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender
40,3108588,1,8,1,14,14.0,False,10258,3,1,...,117,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender
41,3108588,1,8,1,14,14.0,False,25133,4,1,...,21,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender
42,3108588,1,8,1,14,14.0,False,46149,5,0,...,77,7,13.4,both,10,New customer,10,New customer,6.367797,Low spender
43,3108588,1,8,1,14,14.0,False,49235,6,0,...,53,16,1.8,both,10,New customer,10,New customer,6.367797,Low spender
44,2295261,1,9,1,16,0.0,False,49235,1,1,...,53,16,1.8,both,10,New customer,10,New customer,6.367797,Low spender
45,2295261,1,9,1,16,0.0,False,46149,2,1,...,77,7,13.4,both,10,New customer,10,New customer,6.367797,Low spender
46,2295261,1,9,1,16,0.0,False,25133,3,1,...,21,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender
47,2295261,1,9,1,16,0.0,False,196,4,1,...,77,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender
48,2295261,1,9,1,16,0.0,False,10258,5,1,...,117,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender
49,2295261,1,9,1,16,0.0,False,12427,6,1,...,23,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender
50,2550362,1,10,4,8,30.0,False,196,1,1,...,77,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender
51,2550362,1,10,4,8,30.0,False,46149,2,1,...,77,7,13.4,both,10,New customer,10,New customer,6.367797,Low spender
52,2550362,1,10,4,8,30.0,False,39657,3,0,...,45,19,6.8,both,10,New customer,10,New customer,6.367797,Low spender
53,2550362,1,10,4,8,30.0,False,38928,4,0,...,120,16,12.6,both,10,New customer,10,New customer,6.367797,Low spender
54,2550362,1,10,4,8,30.0,False,25133,5,1,...,21,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender
55,2550362,1,10,4,8,30.0,False,10258,6,1,...,117,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender
56,2550362,1,10,4,8,30.0,False,35951,7,0,...,91,16,1.3,both,10,New customer,10,New customer,6.367797,Low spender
57,2550362,1,10,4,8,30.0,False,13032,8,1,...,121,14,4.0,both,10,New customer,10,New customer,6.367797,Low spender
58,2550362,1,10,4,8,30.0,False,12427,9,1,...,23,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender
59,2168274,2,1,2,11,NaN,True,32792,1,0,...,23,19,5.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender
60,2168274,2,1,2,11,NaN,True,47766,2,0,...,24,4,6.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender
61,2168274,2,1,2,11,NaN,True,20574,3,0,...,96,20,2.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender
62,2168274,2,1,2,11,NaN,True,12000,4,0,...,72,13,10.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender
63,2168274,2,1,2,11,NaN,True,48110,5,0,...,78,19,2.7,both,14,Regular customer,14,Regular customer,7.515897,Low spender
64,2168274,2,1,2,11,NaN,True,22474,6,0,...,78,19,4.1,both,14,Regular customer,14,Regular customer,7.515897,Low spender
65,2168274,2,1,2,11,NaN,True,16589,7,0,...,107,19,5.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender
66,2168274,2,1,2,11,NaN,True,35917,8,0,...,98,7,9.4,both,14,Regular customer,14,Regular customer,7.515897,Low spender
67,2168274,2,1,2,11,NaN,True,27344,9,0,...,96,20,14.8,both,14,Regular customer,14,Regular customer,7.515897,Low spender
68,2168274,2,1,2,11,NaN,True,30489,10,0,...,67,20,7.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender
69,2168274,2,1,2,11,NaN,True,27966,11,0,...,123,4,4.4,both,14,Regular customer,14,Regular customer,7.515897,Low spender
70,2168274,2,1,2,11,NaN,True,13176,12,0,...,24,4,10.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender
71,2168274,2,1,2,11,NaN,True,45066,13,0,...,24,4,2.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender
72,1501582,2,2,5,10,10.0,False,16797,1,0,...,24,4,1.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender
73,1501582,2,2,5,10,10.0,False,47526,2,0,...,21,16,2.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender
74,1501582,2,2,5,10,10.0,False,8479,3,0,...,78,19,3.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender
75,1501582,2,2,5,10,10.0,False,47766,4,1,...,24,4,6.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender
76,1501582,2,2,5,10,10.0,False,19051,5,0,...,107,19,3.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender
77,1501582,2,2,5,10,10.0,False,8138,6,0,...,67,20,2.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender
78,1901567,2,3,1,10,3.0,False,47766,1,1,...,24,4,6.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender
79,1901567,2,3,1,10,3.0,False,32792,2,1,...,23,19,5.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender
80,1901567,2,3,1,10,3.0,False,20574,3,1,...,96,20,2.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender
81,1901567,2,3,1,10,3.0,False,7781,4,0,...,21,16,6.6,both,14,Regular customer,14,Regular customer,7.515897,Low spender
82,1901567,2,3,1,10,3.0,False,28874,5,0,...,1,20,6.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender
83,738281,2,4,2,10,8.0,False,49451,1,0,...,67,20,7.1,both,14,Regular customer,14,Regular customer,7.515897,Low spender
84,738281,2,4,2,10,8.0,False,32792,2,1,...,23,19,5.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender
85,738281,2,4,2,10,8.0,False,32139,3,0,...,67,20,7.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender
86,738281,2,4,2,10,8.0,False,34688,4,0,...,31,7,5.8,both,14,Regular customer,14,Regular customer,7.515897,Low spender
87,738281,2,4,2,10,8.0,False,36735,5,0,...,96,20,8.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender
88,738281,2,4,2,10,8.0,False,37646,6,0,...,24,4,9.1,both,14,Regular customer,14,Regular customer,7.515897,Low spender
89,738281,2,4,2,10,8.0,False,22829,7,0,...,78,19,5.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender
90,738281,2,4,2,10,8.0,False,24852,8,0,...,24,4,12.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender
91,738281,2,4,2,10,8.0,False,47209,9,0,...,24,4,4.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender
92,738281,2,4,2,10,8.0,False,33276,10,0,...,67,20,10.8,both,14,Regular customer,14,Regular customer,7.515897,Low spender
93,738281,2,4,2,10,8.0,False,45613,11,0,...,38,1,12.6,both,14,Regular customer,14,Regular customer,7.515897,Low spender
94,738281,2,4,2,10,8.0,False,9681,12,0,...,38,1,2.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender
95,738281,2,4,2,10,8.0,False,21150,13,0,...,38,1,5.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender
96,1673511,2,5,3,11,8.0,False,47144,1,0,...,91,16,14.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender
97,1673511,2,5,3,11,8.0,False,5322,2,0,...,3,19,2.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender
98,1673511,2,5,3,11,8.0,False,17224,3,0,...,3,19,1.6,both,14,Regular customer,14,Regular customer,7.515897,Low spender
99,1673511,2,5,3,11,8.0,False,38656,4,0,...,3,19,3.4,both,14,Regular customer,14,Regular customer,7.515897,Low spender

As a note, there are no high spenders because the average is always lower than 10. This might have to do with the fact that I corrected some price values previously, since there were some outliers.

## 7. Create an order frequency flag

7. In order to send relevant notifications to users within the app (for instance, asking users if they want to buy the same item again), the Instacart team wants you to determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:
- If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
- If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
- If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [77]:
#Crerate column with median values of ordering behavior
ords_prods_merge['median_ordering_behavior'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

/var/folders/1l/dnjb8fld07b4wz73yz4dyxqw0000gn/T/ipykernel_66995/2240365384.py:1: FutureWarning: The provided callable <function median at 0x11058c720> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  ords_prods_merge['median_ordering_behavior'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [79]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_time_hour,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,department_id,prices,match,max_order,loyalty_flag,max_order_2,loyalty_flag_2,average_price_orders,spending_flag,median_ordering_behavior
0,2539329,1,1,2,8,NaN,True,196,1,0,...,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
1,2539329,1,1,2,8,NaN,True,14084,2,0,...,16,12.5,both,10,New customer,10,New customer,6.367797,Low spender,20.5
2,2539329,1,1,2,8,NaN,True,12427,3,0,...,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
3,2539329,1,1,2,8,NaN,True,26088,4,0,...,19,4.7,both,10,New customer,10,New customer,6.367797,Low spender,20.5
4,2539329,1,1,2,8,NaN,True,26405,5,0,...,17,1.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
5,2398795,1,2,3,7,15.0,False,196,1,1,...,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
6,2398795,1,2,3,7,15.0,False,10258,2,0,...,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
7,2398795,1,2,3,7,15.0,False,12427,3,1,...,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
8,2398795,1,2,3,7,15.0,False,13176,4,0,...,4,10.3,both,10,New customer,10,New customer,6.367797,Low spender,20.5
9,2398795,1,2,3,7,15.0,False,26088,5,1,...,19,4.7,both,10,New customer,10,New customer,6.367797,Low spender,20.5
10,2398795,1,2,3,7,15.0,False,13032,6,0,...,14,4.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
11,473747,1,3,3,12,21.0,False,196,1,1,...,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
12,473747,1,3,3,12,21.0,False,12427,2,1,...,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
13,473747,1,3,3,12,21.0,False,10258,3,1,...,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
14,473747,1,3,3,12,21.0,False,25133,4,0,...,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5
15,473747,1,3,3,12,21.0,False,30450,5,0,...,13,3.2,both,10,New customer,10,New customer,6.367797,Low spender,20.5
16,2254736,1,4,4,7,29.0,False,196,1,1,...,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
17,2254736,1,4,4,7,29.0,False,12427,2,1,...,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
18,2254736,1,4,4,7,29.0,False,10258,3,1,...,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
19,2254736,1,4,4,7,29.0,False,25133,4,1,...,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5
20,2254736,1,4,4,7,29.0,False,26405,5,1,...,17,1.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
21,431534,1,5,4,15,28.0,False,196,1,1,...,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
22,431534,1,5,4,15,28.0,False,12427,2,1,...,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
23,431534,1,5,4,15,28.0,False,10258,3,1,...,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
24,431534,1,5,4,15,28.0,False,25133,4,1,...,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5
25,431534,1,5,4,15,28.0,False,10326,5,0,...,4,2.7,both,10,New customer,10,New customer,6.367797,Low spender,20.5
26,431534,1,5,4,15,28.0,False,17122,6,0,...,4,14.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
27,431534,1,5,4,15,28.0,False,41787,7,0,...,4,5.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
28,431534,1,5,4,15,28.0,False,13176,8,1,...,4,10.3,both,10,New customer,10,New customer,6.367797,Low spender,20.5
29,3367565,1,6,2,7,19.0,False,196,1,1,...,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
30,3367565,1,6,2,7,19.0,False,12427,2,1,...,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
31,3367565,1,6,2,7,19.0,False,10258,3,1,...,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
32,3367565,1,6,2,7,19.0,False,25133,4,1,...,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5
33,550135,1,7,1,9,20.0,False,196,1,1,...,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
34,550135,1,7,1,9,20.0,False,10258,2,1,...,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
35,550135,1,7,1,9,20.0,False,12427,3,1,...,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
36,550135,1,7,1,9,20.0,False,25133,4,1,...,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5
37,550135,1,7,1,9,20.0,False,13032,5,1,...,14,4.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
38,3108588,1,8,1,14,14.0,False,12427,1,1,...,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
39,3108588,1,8,1,14,14.0,False,196,2,1,...,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
40,3108588,1,8,1,14,14.0,False,10258,3,1,...,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
41,3108588,1,8,1,14,14.0,False,25133,4,1,...,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5
42,3108588,1,8,1,14,14.0,False,46149,5,0,...,7,13.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
43,3108588,1,8,1,14,14.0,False,49235,6,0,...,16,1.8,both,10,New customer,10,New customer,6.367797,Low spender,20.5
44,2295261,1,9,1,16,0.0,False,49235,1,1,...,16,1.8,both,10,New customer,10,New customer,6.367797,Low spender,20.5
45,2295261,1,9,1,16,0.0,False,46149,2,1,...,7,13.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
46,2295261,1,9,1,16,0.0,False,25133,3,1,...,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5
47,2295261,1,9,1,16,0.0,False,196,4,1,...,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
48,2295261,1,9,1,16,0.0,False,10258,5,1,...,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
49,2295261,1,9,1,16,0.0,False,12427,6,1,...,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
50,2550362,1,10,4,8,30.0,False,196,1,1,...,7,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
51,2550362,1,10,4,8,30.0,False,46149,2,1,...,7,13.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
52,2550362,1,10,4,8,30.0,False,39657,3,0,...,19,6.8,both,10,New customer,10,New customer,6.367797,Low spender,20.5
53,2550362,1,10,4,8,30.0,False,38928,4,0,...,16,12.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5
54,2550362,1,10,4,8,30.0,False,25133,5,1,...,16,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5
55,2550362,1,10,4,8,30.0,False,10258,6,1,...,19,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
56,2550362,1,10,4,8,30.0,False,35951,7,0,...,16,1.3,both,10,New customer,10,New customer,6.367797,Low spender,20.5
57,2550362,1,10,4,8,30.0,False,13032,8,1,...,14,4.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5
58,2550362,1,10,4,8,30.0,False,12427,9,1,...,19,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5
59,2168274,2,1,2,11,NaN,True,32792,1,0,...,19,5.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
60,2168274,2,1,2,11,NaN,True,47766,2,0,...,4,6.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
61,2168274,2,1,2,11,NaN,True,20574,3,0,...,20,2.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
62,2168274,2,1,2,11,NaN,True,12000,4,0,...,13,10.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
63,2168274,2,1,2,11,NaN,True,48110,5,0,...,19,2.7,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
64,2168274,2,1,2,11,NaN,True,22474,6,0,...,19,4.1,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
65,2168274,2,1,2,11,NaN,True,16589,7,0,...,19,5.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
66,2168274,2,1,2,11,NaN,True,35917,8,0,...,7,9.4,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
67,2168274,2,1,2,11,NaN,True,27344,9,0,...,20,14.8,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
68,2168274,2,1,2,11,NaN,True,30489,10,0,...,20,7.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
69,2168274,2,1,2,11,NaN,True,27966,11,0,...,4,4.4,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
70,2168274,2,1,2,11,NaN,True,13176,12,0,...,4,10.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
71,2168274,2,1,2,11,NaN,True,45066,13,0,...,4,2.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
72,1501582,2,2,5,10,10.0,False,16797,1,0,...,4,1.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
73,1501582,2,2,5,10,10.0,False,47526,2,0,...,16,2.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
74,1501582,2,2,5,10,10.0,False,8479,3,0,...,19,3.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
75,1501582,2,2,5,10,10.0,False,47766,4,1,...,4,6.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
76,1501582,2,2,5,10,10.0,False,19051,5,0,...,19,3.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
77,1501582,2,2,5,10,10.0,False,8138,6,0,...,20,2.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
78,1901567,2,3,1,10,3.0,False,47766,1,1,...,4,6.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
79,1901567,2,3,1,10,3.0,False,32792,2,1,...,19,5.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
80,1901567,2,3,1,10,3.0,False,20574,3,1,...,20,2.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
81,1901567,2,3,1,10,3.0,False,7781,4,0,...,16,6.6,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
82,1901567,2,3,1,10,3.0,False,28874,5,0,...,20,6.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
83,738281,2,4,2,10,8.0,False,49451,1,0,...,20,7.1,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
84,738281,2,4,2,10,8.0,False,32792,2,1,...,19,5.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
85,738281,2,4,2,10,8.0,False,32139,3,0,...,20,7.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
86,738281,2,4,2,10,8.0,False,34688,4,0,...,7,5.8,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
87,738281,2,4,2,10,8.0,False,36735,5,0,...,20,8.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
88,738281,2,4,2,10,8.0,False,37646,6,0,...,4,9.1,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
89,738281,2,4,2,10,8.0,False,22829,7,0,...,19,5.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
90,738281,2,4,2,10,8.0,False,24852,8,0,...,4,12.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
91,738281,2,4,2,10,8.0,False,47209,9,0,...,4,4.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
92,738281,2,4,2,10,8.0,False,33276,10,0,...,20,10.8,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
93,738281,2,4,2,10,8.0,False,45613,11,0,...,1,12.6,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
94,738281,2,4,2,10,8.0,False,9681,12,0,...,1,2.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
95,738281,2,4,2,10,8.0,False,21150,13,0,...,1,5.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
96,1673511,2,5,3,11,8.0,False,47144,1,0,...,16,14.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
97,1673511,2,5,3,11,8.0,False,5322,2,0,...,19,2.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
98,1673511,2,5,3,11,8.0,False,17224,3,0,...,19,1.6,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0
99,1673511,2,5,3,11,8.0,False,38656,4,0,...,19,3.4,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0

In [85]:
#Create order_frequency_flag
ords_prods_merge.loc[ords_prods_merge['median_ordering_behavior'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'
ords_prods_merge.loc[(ords_prods_merge['median_ordering_behavior'] > 10) & (ords_prods_merge['median_ordering_behavior'] <= 20), 'order_frequency_flag'] = 'Regular customer'
ords_prods_merge.loc[ords_prods_merge['median_ordering_behavior'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [87]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_time_hour,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,prices,match,max_order,loyalty_flag,max_order_2,loyalty_flag_2,average_price_orders,spending_flag,median_ordering_behavior,order_frequency_flag
0,2539329,1,1,2,8,NaN,True,196,1,0,...,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2539329,1,1,2,8,NaN,True,14084,2,0,...,12.5,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,2539329,1,1,2,8,NaN,True,12427,3,0,...,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2539329,1,1,2,8,NaN,True,26088,4,0,...,4.7,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,2539329,1,1,2,8,NaN,True,26405,5,0,...,1.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
5,2398795,1,2,3,7,15.0,False,196,1,1,...,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
6,2398795,1,2,3,7,15.0,False,10258,2,0,...,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
7,2398795,1,2,3,7,15.0,False,12427,3,1,...,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
8,2398795,1,2,3,7,15.0,False,13176,4,0,...,10.3,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
9,2398795,1,2,3,7,15.0,False,26088,5,1,...,4.7,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
10,2398795,1,2,3,7,15.0,False,13032,6,0,...,4.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
11,473747,1,3,3,12,21.0,False,196,1,1,...,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
12,473747,1,3,3,12,21.0,False,12427,2,1,...,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
13,473747,1,3,3,12,21.0,False,10258,3,1,...,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
14,473747,1,3,3,12,21.0,False,25133,4,0,...,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
15,473747,1,3,3,12,21.0,False,30450,5,0,...,3.2,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
16,2254736,1,4,4,7,29.0,False,196,1,1,...,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
17,2254736,1,4,4,7,29.0,False,12427,2,1,...,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
18,2254736,1,4,4,7,29.0,False,10258,3,1,...,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
19,2254736,1,4,4,7,29.0,False,25133,4,1,...,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
20,2254736,1,4,4,7,29.0,False,26405,5,1,...,1.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
21,431534,1,5,4,15,28.0,False,196,1,1,...,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
22,431534,1,5,4,15,28.0,False,12427,2,1,...,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
23,431534,1,5,4,15,28.0,False,10258,3,1,...,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
24,431534,1,5,4,15,28.0,False,25133,4,1,...,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
25,431534,1,5,4,15,28.0,False,10326,5,0,...,2.7,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
26,431534,1,5,4,15,28.0,False,17122,6,0,...,14.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
27,431534,1,5,4,15,28.0,False,41787,7,0,...,5.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
28,431534,1,5,4,15,28.0,False,13176,8,1,...,10.3,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
29,3367565,1,6,2,7,19.0,False,196,1,1,...,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
30,3367565,1,6,2,7,19.0,False,12427,2,1,...,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
31,3367565,1,6,2,7,19.0,False,10258,3,1,...,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
32,3367565,1,6,2,7,19.0,False,25133,4,1,...,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
33,550135,1,7,1,9,20.0,False,196,1,1,...,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
34,550135,1,7,1,9,20.0,False,10258,2,1,...,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
35,550135,1,7,1,9,20.0,False,12427,3,1,...,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
36,550135,1,7,1,9,20.0,False,25133,4,1,...,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
37,550135,1,7,1,9,20.0,False,13032,5,1,...,4.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
38,3108588,1,8,1,14,14.0,False,12427,1,1,...,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
39,3108588,1,8,1,14,14.0,False,196,2,1,...,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
40,3108588,1,8,1,14,14.0,False,10258,3,1,...,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
41,3108588,1,8,1,14,14.0,False,25133,4,1,...,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
42,3108588,1,8,1,14,14.0,False,46149,5,0,...,13.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
43,3108588,1,8,1,14,14.0,False,49235,6,0,...,1.8,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
44,2295261,1,9,1,16,0.0,False,49235,1,1,...,1.8,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
45,2295261,1,9,1,16,0.0,False,46149,2,1,...,13.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
46,2295261,1,9,1,16,0.0,False,25133,3,1,...,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
47,2295261,1,9,1,16,0.0,False,196,4,1,...,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
48,2295261,1,9,1,16,0.0,False,10258,5,1,...,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
49,2295261,1,9,1,16,0.0,False,12427,6,1,...,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
50,2550362,1,10,4,8,30.0,False,196,1,1,...,9.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
51,2550362,1,10,4,8,30.0,False,46149,2,1,...,13.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
52,2550362,1,10,4,8,30.0,False,39657,3,0,...,6.8,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
53,2550362,1,10,4,8,30.0,False,38928,4,0,...,12.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
54,2550362,1,10,4,8,30.0,False,25133,5,1,...,8.6,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
55,2550362,1,10,4,8,30.0,False,10258,6,1,...,3.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
56,2550362,1,10,4,8,30.0,False,35951,7,0,...,1.3,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
57,2550362,1,10,4,8,30.0,False,13032,8,1,...,4.0,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
58,2550362,1,10,4,8,30.0,False,12427,9,1,...,4.4,both,10,New customer,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
59,2168274,2,1,2,11,NaN,True,32792,1,0,...,5.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
60,2168274,2,1,2,11,NaN,True,47766,2,0,...,6.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
61,2168274,2,1,2,11,NaN,True,20574,3,0,...,2.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
62,2168274,2,1,2,11,NaN,True,12000,4,0,...,10.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
63,2168274,2,1,2,11,NaN,True,48110,5,0,...,2.7,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
64,2168274,2,1,2,11,NaN,True,22474,6,0,...,4.1,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
65,2168274,2,1,2,11,NaN,True,16589,7,0,...,5.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
66,2168274,2,1,2,11,NaN,True,35917,8,0,...,9.4,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
67,2168274,2,1,2,11,NaN,True,27344,9,0,...,14.8,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
68,2168274,2,1,2,11,NaN,True,30489,10,0,...,7.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
69,2168274,2,1,2,11,NaN,True,27966,11,0,...,4.4,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
70,2168274,2,1,2,11,NaN,True,13176,12,0,...,10.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
71,2168274,2,1,2,11,NaN,True,45066,13,0,...,2.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
72,1501582,2,2,5,10,10.0,False,16797,1,0,...,1.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
73,1501582,2,2,5,10,10.0,False,47526,2,0,...,2.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
74,1501582,2,2,5,10,10.0,False,8479,3,0,...,3.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
75,1501582,2,2,5,10,10.0,False,47766,4,1,...,6.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
76,1501582,2,2,5,10,10.0,False,19051,5,0,...,3.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
77,1501582,2,2,5,10,10.0,False,8138,6,0,...,2.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
78,1901567,2,3,1,10,3.0,False,47766,1,1,...,6.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
79,1901567,2,3,1,10,3.0,False,32792,2,1,...,5.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
80,1901567,2,3,1,10,3.0,False,20574,3,1,...,2.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
81,1901567,2,3,1,10,3.0,False,7781,4,0,...,6.6,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
82,1901567,2,3,1,10,3.0,False,28874,5,0,...,6.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
83,738281,2,4,2,10,8.0,False,49451,1,0,...,7.1,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
84,738281,2,4,2,10,8.0,False,32792,2,1,...,5.2,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
85,738281,2,4,2,10,8.0,False,32139,3,0,...,7.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
86,738281,2,4,2,10,8.0,False,34688,4,0,...,5.8,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
87,738281,2,4,2,10,8.0,False,36735,5,0,...,8.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
88,738281,2,4,2,10,8.0,False,37646,6,0,...,9.1,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
89,738281,2,4,2,10,8.0,False,22829,7,0,...,5.5,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
90,738281,2,4,2,10,8.0,False,24852,8,0,...,12.3,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
91,738281,2,4,2,10,8.0,False,47209,9,0,...,4.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
92,738281,2,4,2,10,8.0,False,33276,10,0,...,10.8,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
93,738281,2,4,2,10,8.0,False,45613,11,0,...,12.6,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
94,738281,2,4,2,10,8.0,False,9681,12,0,...,2.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
95,738281,2,4,2,10,8.0,False,21150,13,0,...,5.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
96,1673511,2,5,3,11,8.0,False,47144,1,0,...,14.0,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
97,1673511,2,5,3,11,8.0,False,5322,2,0,...,2.9,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
98,1673511,2,5,3,11,8.0,False,17224,3,0,...,1.6,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer
99,1673511,2,5,3,11,8.0,False,38656,4,0,...,3.4,both,14,Regular customer,14,Regular customer,7.515897,Low spender,13.0,Regular customer

In [89]:
# Check value counts on the spending_flag
ords_prods_merge['order_frequency_flag'].value_counts(dropna = False)

order_frequency_flag
Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: count, dtype: int64

In [95]:
#Check NaN values
missing_values = ords_prods_merge[ords_prods_merge['order_frequency_flag'].isnull() == True]

In [97]:
missing_values

,order_id,user_id,order_number,orders_day_of_week,order_time_hour,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,prices,match,max_order,loyalty_flag,max_order_2,loyalty_flag_2,average_price_orders,spending_flag,median_ordering_behavior,order_frequency_flag
25156870,895835,159838,1,0,17,NaN,True,22198,1,0,...,1.7,both,1,New customer,1,New customer,7.42,Low spender,NaN,NaN
25156871,895835,159838,1,0,17,NaN,True,23695,2,0,...,4.7,both,1,New customer,1,New customer,7.42,Low spender,NaN,NaN
25156872,895835,159838,1,0,17,NaN,True,10749,3,0,...,5.7,both,1,New customer,1,New customer,7.42,Low spender,NaN,NaN
25156873,895835,159838,1,0,17,NaN,True,21334,5,0,...,10.2,both,1,New customer,1,New customer,7.42,Low spender,NaN,NaN
25156874,895835,159838,1,0,17,NaN,True,33401,6,0,...,14.8,both,1,New customer,1,New customer,7.42,Low spender,NaN,NaN

Makes sense since there are missing values in the days_since_prior_order that match clients who have never purchased before.

8. Ensure your notebook is clean and structured and that your code is well commented.

Done.

## 8. Export dataframe

In [ ]:
# Export new dataframe
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge_4_8_task.pkl'))